# Generated by Django 2.2.2 on 2019-07-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='city',
            new_name='paradigm',
        ),
    ]
